triggers:
- envs: []
  last_enabled_at: 2024-04-12 12:37:19.030750
  name: api_to_gcs_trigger
  pipeline_uuid: api_to_gcs
  schedule_interval: '@hourly'
  schedule_type: time
  settings: null
  sla: null
  start_time: 2024-04-12 12:00:00
  status: active
  variables: {}
